const mongoose = require("mongoose");

/**
 * Atomic counter for generating sequential, human-readable identifiers.
 *
 * Usage:
 *   const Counter = require('./Counter');
 *   const next = await Counter.nextValue('caseNumber');
 *   // Returns: 1, 2, 3, ... (monotonically increasing, never reused)
 *
 * The formatted case number is generated by the CaseNumberService,
 * not here. This model only provides the raw sequence value.
 */
const counterSchema = new mongoose.Schema(
  {
    _id: { type: String, required: true }, // e.g. 'caseNumber', 'leadNumber'
    sequence: { type: Number, default: 0 },
  },
  { collection: "counters" }
);

/**
 * Atomically increments the counter for the given key and returns the new value.
 * Uses MongoDB's findOneAndUpdate with upsert to guarantee atomicity.
 * This is safe for concurrent requests — no two calls will return the same value.
 */
counterSchema.statics.nextValue = async function (key) {
  const doc = await this.findOneAndUpdate(
    { _id: key },
    { $inc: { sequence: 1 } },
    { new: true, upsert: true }
  );
  return doc.sequence;
};

module.exports = mongoose.model("Counter", counterSchema);
