// Instant, in-browser email preview. Mirrors Backend emailRenderer.renderCustom()
// in sample mode (substitution + sanitising), but takes the surrounding email
// layout from the server (meta.previewShells - generated by the backend's own
// layoutHtml) so no layout markup is duplicated here and nothing waits on a
// network round trip while typing.
const TOKEN_RE = /\[([a-z][a-z_]*\.[a-z][a-z_]*)\]/g
const EMAIL_ONLY_RE = /^\[([a-z][a-z_]*\.[a-z][a-z_]*)\]$/

export const escapeHtml = (value) => String(value ?? '')
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')

// Same rules as the backend's sanitizeEmailHtml.
export function sanitizeEmailHtml(html) {
  return String(html || '')
    .replace(/<\s*(script|style|iframe|object|embed|link|meta|form)\b[\s\S]*?<\s*\/\s*\1\s*>/gi, '')
    .replace(/<\s*(script|style|iframe|object|embed|link|meta|form)\b[^>]*\/?>/gi, '')
    .replace(/\son[a-z]+\s*=\s*("[^"]*"|'[^']*'|[^\s>]+)/gi, '')
    .replace(/(href|src)\s*=\s*("|')\s*javascript:[^"']*\2/gi, '$1="#"')
}

function substitute(text, samples, { escape, highlightUnknown }) {
  return String(text || '').replace(TOKEN_RE, (match, key) => {
    if (!samples.has(key)) {
      return highlightUnknown && escape
        ? `<mark style="background:#fee2e2;color:#b91c1c;padding:0 2px;border-radius:3px;">${match}</mark>`
        : match
    }
    return escape ? escapeHtml(samples.get(key)) : String(samples.get(key))
  })
}

// A recipient rule -> the sample address shown in the preview header.
function sampleAddress(rule, meta, samples) {
  if (rule.type !== 'custom') return meta.recipientTypes.find((entry) => entry.type === rule.type)?.sample
  const token = EMAIL_ONLY_RE.exec(String(rule.value || '').trim())
  return token && samples.has(token[1]) ? samples.get(token[1]) : rule.value
}

export function renderPreview({ subject, heading, body, triggerKey, recipients }, meta) {
  const samples = new Map(meta.variables.map((variable) => [variable.key, variable.sample]))
  const shells = meta.previewShells
  const renderedSubject = substitute(subject, samples, { escape: false })
  const renderedHeading = heading ? substitute(heading, samples, { escape: true, highlightUnknown: true }) : ''
  const renderedBody = substitute(sanitizeEmailHtml(body), samples, { escape: true, highlightUnknown: true })

  const html = (renderedHeading ? shells.withHeading : shells.withoutHeading)
    .split(shells.tokens.title).join(escapeHtml(renderedSubject))
    .split(shells.tokens.heading).join(renderedHeading)
    .split(shells.tokens.body).join(renderedBody)

  const lists = recipients || {}
  const sampleList = (rules) => (rules || []).map((rule) => sampleAddress(rule, meta, samples)).filter(Boolean)
  let to = sampleList(lists.to)
  if (!to.length) {
    const trigger = meta.triggers.find((entry) => entry.key === triggerKey)
    const type = trigger?.recipient === 'team_member' ? 'case_manager' : trigger?.recipient || 'client'
    to = [meta.recipientTypes.find((entry) => entry.type === type)?.sample || 'john.smith@example.com']
  }
  return { from: meta.fromName || 'Immiglance', to, cc: sampleList(lists.cc), bcc: sampleList(lists.bcc), subject: renderedSubject, html }
}
