const router = require("express").Router();
const authenticate = require("../../middleware/authenticate");
const authorizeRoles = require("../../middleware/authorizeRoles");
const authorizePermissions = require("../../middleware/authorizePermissions");
const ctrl = require("./uscis-form.controller");

router.get("/", authenticate, authorizePermissions("forms:read"), ctrl.list);
router.post("/", authenticate, authorizeRoles("super_admin"), authorizePermissions("forms:create"), ctrl.create);
router.get("/registry", authenticate, authorizePermissions("forms:read"), ctrl.listRegistry);
router.get("/registry/active", authenticate, authorizePermissions("forms:read"), ctrl.listActiveEditions);
router.get("/registry/archived", authenticate, authorizePermissions("forms:read"), ctrl.listArchivedEditions);
router.get("/registry/:formCode/versions", authenticate, authorizePermissions("forms:read"), ctrl.getVersions);
router.get("/sync/history", authenticate, authorizeRoles("super_admin", "admin"), authorizePermissions("forms:check_updates"), ctrl.getSyncHistory);
router.post("/sync", authenticate, authorizeRoles("super_admin", "admin"), authorizePermissions("forms:check_updates"), ctrl.syncForms);
router.post("/definitions/validate", authenticate, authorizeRoles("super_admin", "admin"), authorizePermissions("forms:create"), ctrl.validateDefinition);
router.post("/definitions/import", authenticate, authorizeRoles("super_admin", "admin"), authorizePermissions("forms:create"), ctrl.importDefinition);
router.post("/check-updates", authenticate, authorizeRoles("super_admin", "admin"), authorizePermissions("forms:check_updates"), ctrl.checkUpdates);
router.get("/case", authenticate, authorizePermissions("forms:read"), ctrl.getAllCaseForms);
router.get("/case/:caseId", authenticate, authorizePermissions("forms:read"), ctrl.getCaseForms);
router.post("/case/:caseId", authenticate, authorizePermissions("forms:create"), ctrl.createCaseForm);
router.get("/case/:caseId/:formId/render", authenticate, authorizePermissions("forms:read"), ctrl.renderCaseForm);
router.get("/case/:caseId/:formId/validation", authenticate, authorizePermissions("forms:read"), ctrl.validateCaseForm);
router.get("/case/:caseId/:formId/comparison", authenticate, authorizePermissions("forms:read"), ctrl.compareCaseForm);
router.put("/case/:caseId/:formId/draft", authenticate, authorizePermissions("forms:update"), ctrl.saveDraft);
router.put("/case/:caseId/:formId/autosave", authenticate, authorizePermissions("forms:update"), ctrl.autoSave);
router.put("/case/:caseId/:formId/section", authenticate, authorizePermissions("forms:update"), ctrl.saveSection);
router.post("/case/:caseId/:formId/review", authenticate, authorizePermissions("forms:update"), ctrl.reviewCaseForm);
router.get("/case/:caseId/:formId/workspace", authenticate, authorizePermissions("forms:read"), ctrl.openInteractiveForm);
router.patch("/case/:caseId/:formId/workspace/field", authenticate, authorizePermissions("forms:update"), ctrl.saveInteractiveField);
router.put("/case/:caseId/:formId/workspace/section", authenticate, authorizePermissions("forms:update"), ctrl.saveInteractiveSection);
router.post("/case/:caseId/:formId/workspace/field/review", authenticate, authorizePermissions("forms:update"), ctrl.reviewInteractiveField);
router.post("/case/:caseId/:formId/workspace/section/review", authenticate, authorizePermissions("forms:update"), ctrl.reviewInteractiveSection);
router.post("/case/:caseId/:formId/workspace/decision", authenticate, authorizePermissions("forms:approve"), ctrl.decideInteractiveForm);
router.post("/case/:caseId/:formId/workspace/lock", authenticate, authorizePermissions("forms:approve"), ctrl.lockInteractiveForm);
router.post("/case/:caseId/:formId/workspace/refresh", authenticate, authorizePermissions("forms:update"), ctrl.refreshInteractiveForm);
router.post("/case/:caseId/:formId/workspace/reset", authenticate, authorizePermissions("forms:update"), ctrl.resetInteractiveForm);
router.post("/case/:caseId/:formId/workspace/conflict", authenticate, authorizePermissions("forms:update"), ctrl.resolveInteractiveConflict);
router.post("/case/:caseId/:formId/workspace/history/:historyId/rollback", authenticate, authorizePermissions("forms:update"), ctrl.rollbackInteractiveField);
router.get("/case/:caseId/:formId/workspace/validation", authenticate, authorizePermissions("forms:read"), ctrl.getInteractiveValidation);
router.get("/case/:caseId/:formId/workspace/comments", authenticate, authorizePermissions("forms:read"), ctrl.getInteractiveComments);
router.post("/case/:caseId/:formId/workspace/comments", authenticate, authorizePermissions("forms:update"), ctrl.addInteractiveComment);
router.patch("/case/:caseId/:formId/workspace/comments/:commentId/resolve", authenticate, authorizePermissions("forms:update"), ctrl.resolveInteractiveComment);
router.post("/case/:caseId/:formId/workspace/tasks", authenticate, authorizePermissions("tasks:create"), ctrl.createInteractiveTask);
router.get("/case/:caseId/:formId/workspace/history", authenticate, authorizePermissions("forms:read"), ctrl.getInteractiveHistory);
router.get("/case/:caseId/:formId/workspace/sources", authenticate, authorizePermissions("forms:read"), ctrl.getInteractiveSources);
router.get("/case/:caseId/:formId/workspace/comparison", authenticate, authorizePermissions("forms:read"), ctrl.getInteractiveComparison);
router.get("/case/:caseId/:formId/workspace/search", authenticate, authorizePermissions("forms:read"), ctrl.searchInteractiveFields);
router.get("/:id", authenticate, authorizePermissions("forms:read"), ctrl.get);
router.put("/:id", authenticate, authorizeRoles("super_admin"), authorizePermissions("forms:update"), ctrl.update);
router.delete("/:id", authenticate, authorizeRoles("super_admin"), authorizePermissions("forms:delete"), ctrl.remove);
router.put("/:id/approve", authenticate, authorizeRoles("super_admin", "admin"), authorizePermissions("forms:approve"), ctrl.approveTemplate);
router.put("/:id/activate", authenticate, authorizeRoles("super_admin", "admin"), authorizePermissions("forms:approve"), ctrl.activateTemplate);
router.put("/:id/archive", authenticate, authorizeRoles("super_admin", "admin"), authorizePermissions("forms:update"), ctrl.archiveTemplate);
router.put("/:id/rollback", authenticate, authorizeRoles("super_admin", "admin"), authorizePermissions("forms:approve"), ctrl.rollbackTemplate);

module.exports = router;
